language: csharp
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - memcached
matrix:
  include:
    - dotnet: 1.0.1
      mono: none
      env: DOTNETCORE=1    
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
mono: none
os:
  - linux
branches:
  only:
    - master
    - release
    - dev
    - migrate-tests-to-core
script:
  - ./build.sh
  - ./run-test.sh
#notifications:
#  webhooks:
#    secure: ""
#  on_success: always
#  on_failure: always
#  on_start: always
